### ISSUE TITLE
Document support

### ISSUE THREAD

**Issue by underthestars-zhy** [swift-onedrive/microsoft-graph-core#1]
I need some documents to start my app with this package, such as haw I can upload file or get token

**Comment by VineFiner** [comment]
> I need some documents to start my app with this package, such as haw I can upload file or get token

This is can run demo

https://github.com/swift-onedrive/microsoft-graph-commands

**Comment by VineFiner** [comment]
I was inspired by him。
 https://github.com/vapor-community/google-cloud-kit

There may be documentation
https://forums.swift.org/t/support-hosting-docc-archives-in-static-hosting-environments/53572/7
